# 08 — A First Taste of numpy and pandas

Builds on [[07_modules_and_classes]]. This is the last notebook in the course. Everything so
far has been pure Python (the standard library only). Here's a quick look at two libraries
you'll use constantly once you move into data science and machine learning: `numpy` (fast
numeric arrays) and `pandas` (tables of data, like a spreadsheet in code).

This is intentionally brief — just enough to recognize the shape of the tools before you go
deeper elsewhere.

## Setup

This notebook needs `numpy` and `pandas` installed. If you don't have them yet, run this in
a terminal (not in the notebook):

```
pip install numpy pandas
```

## Why not just use lists?

You already know Python's `list`. `numpy` gives you an *array* type instead, which is much
faster for numeric work and lets you apply operations to every element at once ("vectorized"
operations) without writing a `for` loop.

In [1]:
import sys


try:
    import numpy as np
except ImportError:
    print("Numpy is not installed.")
    # Now we will pip install numpy on the fly
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "numpy"])
    import numpy as np

numbers = [1, 2, 3, 4, 5]      # a plain Python list
arr = np.array(numbers)         # a numpy array holding the same values

print(arr)
print(type(arr))
print(arr * 2)   # multiplies every element by 2, no loop needed

[1 2 3 4 5]
<class 'numpy.ndarray'>
[ 2  4  6  8 10]


### Your turn

Create a numpy array from the list `[10, 20, 30, 40]`, then print the array with `5` added
to every element (again, no loop — just `+`).

In [ ]:
import numpy as np

values = [10, 20, 30, 40]
val = np.array(values)
print(val *2)


# TODO: convert values to a numpy array, then print it with 5 added to each element
...


[20 40 60 80]
100


Ellipsis

## A few numpy basics

Arrays have useful built-in aggregate methods: `.sum()`, `.mean()`, `.max()`, `.min()`. These
mirror what you'd otherwise write by hand with loops and the `statistics` module.

In [5]:
scores = np.array([85, 92, 78, 90, 88])

print(scores.sum())
print(scores.mean())
print(scores.max())

433
86.6
92


### Your turn

Given the array below, print its mean and its max in one f-string, e.g.
`"mean: 15.0, max: 30"`.

In [7]:
data = np.array([10, 15, 20, 30, 0])
print(f"Mean: {data.mean()} Max: {data.max()} ")

# TODO: print an f-string with the mean and max
...

Mean: 15.0 Max: 30 


Ellipsis

## pandas: tables of data

A pandas `DataFrame` is a table — rows and columns, like a spreadsheet or a database table.
You typically build one from a dictionary mapping column names to lists of values.

In [8]:
try:
    import pandas as pd
except ImportError:
    print("Pandas is not installed.")
    # Now we will pip install pandas on the fly
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas"])
    import pandas as pd

data = {
    "name": ["Ada", "Alan", "Grace"],
    "age": [36, 41, 85],
}
df = pd.DataFrame(data)
print(df)

Pandas is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 30.5 MB/s  0:00:00eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
    name  age
0    Ada   36
1   Alan   41
2  Grace   85


Access a column like a dict key (`df["age"]`); it comes back as a pandas `Series`, which
behaves a lot like a numpy array — including supporting `.mean()`, `.max()`, etc.

In [9]:
print(df["age"])
print(df["age"].mean())

0    36
1    41
2    85
Name: age, dtype: int64
54.0


### Your turn

Build a `DataFrame` from the dictionary below, then print the `"score"` column's mean.

In [15]:
import pandas as pd

data = {
    "name": ["Sam", "Robin", "Jess"],
    "score": [72, 88, 95],
}

# TODO: build a DataFrame from data, then print the mean of the "score" column
df = pd.DataFrame(data)
print(df["score"].mean())


85.0


## Filtering rows

You can filter a `DataFrame` using a boolean condition on a column, similar to the `if`
conditions you've written throughout this course — pandas applies the condition to every row
at once.

In [18]:
df = pd.DataFrame({
    "name": ["Ada", "Alan", "Grace", "Linus"],
    "age": [36, 41, 85, 54],
})

adults_over_40 = df[df["age"] > 40]
print(adults_over_40)

    name  age
1   Alan   41
2  Grace   85
3  Linus   54


### Your turn

From the `DataFrame` below, filter to just the rows where `"passed"` is `True`, and print
the result.

In [22]:
df = pd.DataFrame({
    "student": ["Sam", "Robin", "Jess", "Kai"],
    "passed": [True, False, True, True],
})

# TODO: filter to rows where passed is True
passing_students = df[df["passed"] == True]
print(passing_students)

  student  passed
0     Sam    True
2    Jess    True
3     Kai    True


## Recap

- `numpy` arrays (`np.array(...)`) support fast, loop-free ("vectorized") math and handy
  aggregates like `.sum()`, `.mean()`, `.max()`.
- `pandas` `DataFrame`s represent tables of data, usually built from a dict of columns.
- Access a column with `df["column_name"]`; filter rows with a boolean condition like
  `df[df["column"] > value]`.
- This is just enough to recognize the shape of these tools — there's a lot more to learn
  as you move into data science and machine learning from here.

### Combined exercise

Build a `DataFrame` from the `data` dict below (columns `"city"` and `"temperature"`). Print
the mean temperature, then print just the rows where `"temperature"` is above that mean.

In [ ]:
data = {
    "city": ["Perth", "Sydney", "Hobart", "Darwin"],
    "temperature": [31, 24, 15, 34],
}

# TODO: build the DataFrame, compute the mean temperature,
# then print rows where temperature is above the mean
df = pd.DataFrame(data) # convers the standard data set into pandas set
mean_temp = df["temperature"].mean() # filters out the temperature collum and then applys the avg
above_average = df[df["temperature"] > mean_temp] #applys the condition
print(above_average)

     city  temperature
0   Perth           31
3  Darwin           34
